(defpackage #:cl-android/cffi
  (:use #:cl #:cffi)
  (:export #:libandroid
           #:pid
           #:getpid
           #:uid
           #:getuid
           #:get-application-target-api-level
           #:get-device-api-level
           #:check-permission-result
           #:check-permission-status
           #:check-permission))

(defpackage #:cl-android
  (:use #:cl #:cffi)
  (:local-nicknames (#:android #:cl-android/cffi))
  (:import-from #:cl-android/cffi
                #:get-application-target-api-level
                #:get-device-api-level)
  (:export #:init
           #:quit
           #:get-application-target-api-level
           #:get-device-api-level
           #:check-permission))

(defpackage #:cl-android/jni/cffi
  (:use #:cffi)
  (:export #:native-helper

           #:java-boolean
           #:java-byte
           #:java-char
           #:java-short
           #:java-int
           #:java-long
           #:java-float
           #:java-double
           #:java-size

           #:java-object
           #:java-class
           #:java-string
           #:java-array
           #:java-object-array
           #:java-boolean-array
           #:java-byte-array
           #:java-char-array
           #:java-short-array
           #:java-int-array
           #:java-long-array
           #:java-float-array
           #:java-double-array
           #:java-throwable
           #:java-weak
           #:java-field-id
           #:java-method-id

           #:java-value
           #:boolean
           #:byte
           #:char
           #:short
           #:int
           #:long
           #:float
           #:double
           #:object

           #:java-object-reference-type

           #:jni-native-method
           #:name
           #:signature
           #:function-pointer

           #:jni-native-interface

           #:get-version
           #:reserved-0
           #:reserved-1
           #:reserved-2
           #:reserved-3
           #:get-version
           #:define-class
           #:find-class
           #:from-reflected-method
           #:from-reflected-field
           #:to-reflected-method
           #:get-superclass
           #:is-assignable-from
           #:to-reflected-field
           #:throw
           #:throw-new
           #:exception-occurred
           #:exception-describe
           #:exception-clear
           #:fatal-error
           #:push-local-frame
           #:pop-local-frame
           #:new-global-reference
           #:delete-global-reference
           #:delete-local-reference
           #:is-same-object
           #:new-local-reference
           #:ensure-local-capacity
           #:alloc-object
           #:new-object
           #:new-object-v
           #:new-object-a
           #:get-object-class
           #:is-instance-of
           #:get-method-id
           #:call-object-method
           #:call-object-method-v
           #:call-object-method-a
           #:call-boolean-method
           #:call-boolean-method-v
           #:call-boolean-method-a
           #:call-byte-method
           #:call-byte-method-v
           #:call-byte-method-a
           #:call-char-method
           #:call-char-method-v
           #:call-char-method-a
           #:call-short-method
           #:call-short-method-v
           #:call-short-method-a
           #:call-int-method
           #:call-int-method-v
           #:call-int-method-a
           #:call-long-method
           #:call-long-method-v
           #:call-long-method-a
           #:call-float-method
           #:call-float-method-v
           #:call-float-method-a
           #:call-double-method
           #:call-double-method-v
           #:call-double-method-a
           #:call-void-method
           #:call-void-method-v
           #:call-void-method-a
           #:call-nonvirtual-object-method
           #:call-nonvirtual-object-method-v
           #:call-nonvirtual-object-method-a
           #:call-nonvirtual-boolean-method
           #:call-nonvirtual-boolean-method-v
           #:call-nonvirtual-boolean-method-a
           #:call-nonvirtual-byte-method
           #:call-nonvirtual-byte-method-v
           #:call-nonvirtual-byte-method-a
           #:call-nonvirtual-char-method
           #:call-nonvirtual-char-method-v
           #:call-nonvirtual-char-method-a
           #:call-nonvirtual-short-method
           #:call-nonvirtual-short-method-v
           #:call-nonvirtual-short-method-a
           #:call-nonvirtual-int-method
           #:call-nonvirtual-int-method-v
           #:call-nonvirtual-int-method-a
           #:call-nonvirtual-long-method
           #:call-nonvirtual-long-method-v
           #:call-nonvirtual-long-method-a
           #:call-nonvirtual-float-method
           #:call-nonvirtual-float-method-v
           #:call-nonvirtual-float-method-a
           #:call-nonvirtual-double-method
           #:call-nonvirtual-double-method-v
           #:call-nonvirtual-double-method-a
           #:call-nonvirtual-void-method
           #:call-nonvirtual-void-method-v
           #:call-nonvirtual-void-method-a
           #:get-field-id
           #:get-object-field
           #:get-boolean-field
           #:get-byte-field
           #:get-char-field
           #:get-short-field
           #:get-int-field
           #:get-long-field
           #:get-float-field
           #:get-double-field
           #:set-object-field
           #:set-boolean-field
           #:set-byte-field
           #:set-char-field
           #:set-short-field
           #:set-int-field
           #:set-long-field
           #:set-float-field
           #:set-double-field
           #:get-static-method-id
           #:call-static-object-method
           #:call-static-object-method-v
           #:call-static-object-method-a
           #:call-static-boolean-method
           #:call-static-boolean-method-v
           #:call-static-boolean-method-a
           #:call-static-byte-method
           #:call-static-byte-method-v
           #:call-static-byte-method-a
           #:call-static-char-method
           #:call-static-char-method-v
           #:call-static-char-method-a
           #:call-static-short-method
           #:call-static-short-method-v
           #:call-static-short-method-a
           #:call-static-int-method
           #:call-static-int-method-v
           #:call-static-int-method-a
           #:call-static-long-method
           #:call-static-long-method-v
           #:call-static-long-method-a
           #:call-static-float-method
           #:call-static-float-method-v
           #:call-static-float-method-a
           #:call-static-double-method
           #:call-static-double-method-v
           #:call-static-double-method-a
           #:call-static-void-method
           #:call-static-void-method-v
           #:call-static-void-method-a
           #:get-static-field-id
           #:get-static-object-field
           #:get-static-boolean-field
           #:get-static-byte-field
           #:get-static-char-field
           #:get-static-short-field
           #:get-static-int-field
           #:get-static-long-field
           #:get-static-float-field
           #:get-static-double-field
           #:set-static-object-field
           #:set-static-boolean-field
           #:set-static-byte-field
           #:set-static-char-field
           #:set-static-short-field
           #:set-static-int-field
           #:set-static-long-field
           #:set-static-float-field
           #:set-static-double-field
           #:new-string
           #:get-string-length
           #:get-string-chars
           #:release-string-chars
           #:new-string-utf
           #:get-string-utf-length
           #:get-string-utf-chars
           #:release-string-utf-chars
           #:get-array-length
           #:new-object-array
           #:get-object-array-element
           #:set-object-array-element
           #:new-boolean-array
           #:new-byte-array
           #:new-char-array
           #:new-short-array
           #:new-int-array
           #:new-long-array
           #:new-float-array
           #:new-double-array
           #:get-boolean-array-elements
           #:get-byte-array-elements
           #:get-char-array-elements
           #:get-short-array-elements
           #:get-int-array-elements
           #:get-long-array-elements
           #:get-float-array-elements
           #:get-double-array-elements
           #:release-boolean-array-elements
           #:release-byte-array-elements
           #:release-char-array-elements
           #:release-short-array-elements
           #:release-int-array-elements
           #:release-long-array-elements
           #:release-float-array-elements
           #:release-double-array-elements
           #:get-boolean-array-region
           #:get-byte-array-region
           #:get-char-array-region
           #:get-short-array-region
           #:get-int-array-region
           #:get-long-array-region
           #:get-float-array-region
           #:get-double-array-region
           #:set-boolean-array-region
           #:set-byte-array-region
           #:set-char-array-region
           #:set-short-array-region
           #:set-int-array-region
           #:set-long-array-region
           #:set-float-array-region
           #:set-double-array-region
           #:register-natives
           #:unregister-natives
           #:monitor-enter
           #:monitor-exit
           #:get-java-vm
           #:get-string-region
           #:get-string-utf-region
           #:get-primitive-array-critical
           #:release-primitive-array-critical
           #:get-string-critical
           #:release-string-critical
           #:new-weak-global-reference
           #:delete-weak-global-reference
           #:exception-check
           #:new-direct-byte-buffer
           #:get-direct-buffer-address
           #:get-direct-buffer-capacity
           #:get-object-reference-type

           #:jni-invoke-interface
           #:destroy-java-vm
           #:attach-current-thread
           #:detach-current-thread
           #:get-environment
           #:attach-current-thread-as-daemon
           #:c-jni-environment
           #:jni-environment
           #:java-vm
           #:jni-version

           #:java-vm-attach-args

           #:version
           #:name
           #:group
           #:java-vm-option

           #:option-string
           #:extra-information
           #:java-vm-initargs

           #:version
           #:options-number
           #:options
           #:ignore-unrecognized
           #:return-code

           #:get-default-java-vm-initargs
           #:create-java-vm
           #:get-created-java-vms))

(defpackage #:cl-android/jni
  (:use #:cl #:cffi)
  (:local-nicknames (#:jni #:cl-android/jni/cffi))
  (:export #:init
           #:get-created-java-vms
           #:destroy-java-vm
           #:attach-current-thread
           #:detach-current-thread
           #:get-environment))
